### ISSUE TITLE
Support custom http.Client for APIRegistrar

### ISSUE THREAD

**Issue by cohosh** [refraction-networking/gotapdance#113]
I'm going through to process of adapting the Tor Conjure PT to use the latest version of the gotapdance library, and there have been significant changes since version 1.3.0 (as an aside, I highly recommend using [semantic versioning](https://semver.org/) in the future to signal breaking API changes).

Before, I implemented domain fronting by setting the `APIRegistrarBidirectional.Client` to my own `http.Client` with the appropriate front domain. See the excerpt from [client/registration.go](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/conjure/-/blob/a73326edc0a0022f1763608d7897bcd06cfc0ee7/client/registration.go#L73):
```golang
    // APIRegistrarBidirectional expects an HTTP client for sending the registration request.
    // The http.RoundTripper associated with this client dictates the censorship-resistant
    // rendezvous method used to establish a connection with the registration server.
    // As of now, the deployed Conjure station supports direct HTTP connections and domain
    // fronted connections.
    registrar.Client = &http.Client{
        Transport: &Rendezvous{
            registerURL: config.registerURL,
            front:       config.front,
            transport:   transport,
        },
    }
```

However, this is no longer exposed. The easiest ways I can think to do this are:
- export a `SetHTTPClient` function that allows the caller to pass an `http.Client` to it (different from how [`setHTTPClient`](https://github.com/refraction-networking/gotapdance/blob/master/pkg/registration/api-registrar.go#L149) currently works), or
- add an `HTTPClient` field to `registration.Config`

**Comment by jmwample** [comment]
You are totally right. I overlooked this as a breaking change as we refactored some of the registrars into a more generic interface. 
 
I will look into a clean solution to make that feature available again.

**Comment by cohosh** [comment]
Thanks! There's no rush on this since we're using the `v1.3.0` just fine for now. Let me know if you'd like me to do the legwork and submit an MR.

**Comment by jmwample** [comment]
I think that @mingyech said he is going to take a pass on it. Just as a heads up relating to updating versions, we are hoping to land https://github.com/refraction-networking/gotapdance/pull/108 soon (though it definitely needs a pass for breaking changes!).

**Comment by mingyech** [comment]
Should be fixed in #114, I added the ability to do this by passing an `HTTPClient` in `registration.Config`.

**Comment by cohosh** [comment]
Thanks!

**Comment by cohosh** [comment]
Just to follow up on this, do you know when there will be a new version release so that I can update this dependency?

**Comment by jmwample** [comment]
It will likely be early next week, unless I end up getting to it this weekend. Sorry for the delay, we had several other things pop up that took precedence. This is the main blocker now for several other features we are hoping to test in production ASAP.

**Comment by cohosh** [comment]
Awesome! No rush on my side, next week is perfect.
