### ISSUE TITLE
fix travis CI build

### ISSUE THREAD

**Issue by jmwample** [refraction-networking/gotapdance#16]
travis CI is broken and errors on building android app 

build process is probably out of date from what Psiphon sent in the past.

**Comment by sergeyfrolov** [comment]
Fixed in #17

**Comment by jmwample** [comment]
Master fixed in commit d6cb3725f991a3f0f23376edc67a571df518d3e4

- [x] conjure: Fixed in #17 
- [x] master: fixed in d6cb3725f991a3f0f23376edc67a571df518d3e4
