### ISSUE TITLE
Covert address with port 0

### ISSUE THREAD

**Issue by jmwample** [refraction-networking/gotapdance#32]
Registrations are getting through from the psiphon clients with port set to 0. This fails to dial once registered with the station. 

Failing early i.e. before registering or connecting on the client would save resources across the board.

**Comment by sergeyfrolov** [comment]
Is this issue "do not dial, if the covert address is invalid, e.g. the port is 0?"

**Comment by jmwample** [comment]
No, we were getting addresses from the psiphon APK where the `address:port` after nethost split was `x.x.x.x:0`. We added logging in the dialer but I haven't seen this happen again since then. 

@ewust did we do anything to resolve this directly?
